### ISSUE TITLE
Doesn't work with Unity 4.2.2 / Xcode 5.0

### ISSUE THREAD

**Issue by drjeffnorris** [sphero-inc/Sphero-AR-SDK#2]
Hi - I'd really like to use this, but I can't get the examples to build with Unity 4.22 and Xcode 5.0.  There's a trivial change of AppController.h to UnityAppController.h but some very non-trivial problems during linking.  Here's the one that I'm currently blocked on:

Undefined symbols for architecture armv7:
  "_sMotionManager", referenced from:
      -[ARUNBridge_iOS initializeEngineWithCameraMode:] in ARUNBridge.o
ld: symbol(s) not found for architecture armv7
